#include <cassert>
#include <cstdio>
#include <iostream>
#include <memory>
#include <string>

// this hpp give a define of yyparse that generated by bison
#include "parser.tab.hpp"

using namespace std;

// defined in code that generated by flex
extern FILE *yyin;

int main(int argc, const char *argv[]) {
  assert(argc == 2);
  auto input = argv[1];

  yyin = fopen(input, "r");
  assert(yyin);

  unique_ptr<string> ast;
  auto ret = yyparse(ast);
  assert(!ret);

  std::cout << "AST: " << std::endl;
  if (ast) {
    cout << *ast << endl;
  } else {
    cout << "[empty]" << endl;
  }
  return 0;
}
